---
title: "dst_assessment1"
author: "Wenqi Fang"
date: "19/11/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## R part of assessment

## Header content


required libraries:
```{r}
if (!require("e1071")) install.packages("e1071")
if (!require("gmodels")) install.packages("gmodels")
library(e1071) # for training the data
library(gmodels) # For evaluating the model performance
```


load and name the data:
```{r}
kdd.train <- read.csv(file="D:\\SSS\\MSC\\dst\\data\\ass1\\new\\new\\kddcup99_train.csv", header=F)
kdd.test1 <- read.csv(file="D:\\SSS\\MSC\\dst\\data\\ass1\\new\\new\\kddcup99_test.csv", header=F)
kdd.test2 <- read.csv(file="D:\\SSS\\MSC\\dst\\data\\ass1\\new\\new\\kddcup99_test2.csv", header=F)
kddnames<-read.csv(file="D:\\SSS\\MSC\\dst\\data\\kddcup.names.txt")
colnames(kdd.train)=c(kddnames[,1],"label")
colnames(kdd.test1)=c(kddnames[,1],"label")
colnames(kdd.test2)=c(kddnames[,1],"label")
```

coverts label column to factor:
```{r}
kdd.train$label<-as.factor(kdd.train$label)
kdd.test1$label<-as.factor(kdd.test1$label)
kdd.test2$label<-as.factor(kdd.test2$label)
kdd.train
kdd.test1
kdd.test2
```


## train a model on data

```{r}
model<-naiveBayes(label~., data=kdd.train) #use the naivebayes() function to train data
pred1<-predict(model,kdd.test1[-42]) #classify test data
pred1
```

classify the second test data:
```{r}
pred2<-predict(model,kdd.test2[-42])
pred2
```


## evaluate the model performance

```{r}
CrossTable(x=kdd.test1$label,y=pred1)
CrossTable(x=kdd.test2$label,y=pred2)
```



